export const committees = [
    {
        id: "executives",
        name: "The Executives",
        members: [
            {
                id: "breanna-powell",
                name: "Breanna Powell",
                role: "Marketing Lead",
                photo: "/MeetTheTeamPhotos/breanna-powell.jpg",
                link: "https://www.linkedin.com/in/breanna-powell-wa/",
            },
            {
                id: "chinmayee-chadalavada",
                name: "Chin Chadalavada",
                role: "Sponsorships Outreach Lead",
                photo: "/MeetTheTeamPhotos/chinmayee-chadalavada.jpg",
                link: "https://www.linkedin.com/in/chinmayee-chadalavada-4279a4243/",
            },
            {
                id: "hannah-kim",
                name: "Hannah Kim",
                role: "Production Management Lead",
                photo: "/MeetTheTeamPhotos/hannah-kim.jpg",
                link: "https://www.linkedin.com/in/hannah-hanul/",
            },
            {
                id: "sai-bathina",
                name: "Sai Bathina",
                role: "Avanade Rep, Content and Design Co-lead",
                photo: "/MeetTheTeamPhotos/sai-bathina.jpg",
                link: "https://www.linkedin.com/in/saikanishkbathina/",
            },
            {
                id: "simon-dao",
                name: "Simon Dao",
                role: "Website Development Lead",
                photo: "/MeetTheTeamPhotos/simon-dao.jpg",
                link: "https://www.linkedin.com/in/simon-dao/",
            },
            {
                id: "vinaya-chava",
                name: "Vinaya Chava",
                role: "Local Arrangements Lead",
                photo: "/MeetTheTeamPhotos/vinaya-chava.jpg",
                link: "https://www.linkedin.com/in/vinayachava/",
            },
        ],
    },
    {
        id: "committee-leads",
        name: "Justice Leads",
        members: [
            {
                id: "jui-bangali",
                name: "Jui Bangali",
                role: "WiCyS President, Local Arrangments Member, Product Management Member",
                photo: "/MeetTheTeamPhotos/jui-bangali.jpg",
                link: "https://www.linkedin.com/in/jui-bangali/",
            },
            {
                id: "ruthie-lartey",
                name: "Ruthie Lartey",
                role: "ACM-W, Content and Design Co-lead, Marketing Member",
                photo: "/MeetTheTeamPhotos/ruthie-lartey.jpg",
                link: "https://www.linkedin.com/in/ruthie-lartey/",
            }
        ],
    },
    {
        id: "content-design",
        name: "Content Design Champions",
        members: [
            {
                id: "simon-dao",
                name: "Simon Dao",
                role: "Content and Design Lead",
                photo: "/MeetTheTeamPhotos/simon-dao.jpg",
                link: "https://www.linkedin.com/in/simon-dao/",
            },
            {
                id: "ruthie-lartey",
                name: "Ruthie Lartey",
                role: "ACM-W, Content and Design Co-lead, Marketing Member",
                photo: "/MeetTheTeamPhotos/ruthie-lartey.jpg",
                link: "https://www.linkedin.com/in/ruthie-lartey/",
            },
            {
                id: "sai-bathina",
                name: "Sai Bathina",
                role: "Avanade Rep, Content and Design Co-lead",
                photo: "/MeetTheTeamPhotos/sai-bathina.jpg",
                link: "https://www.linkedin.com/in/saikanishkbathina/",
            },
            {
                id: "jingyi-zhong",
                name: "Jingyi Zhong",
                role: "Web Designer",
                photo: "/MeetTheTeamPhotos/default.jpg",
                link: "https://www.linkedin.com/in/zhongjy/",
            },
        ],
    },
    {
        id: "digital-experience",
        name: "Digital Daredevils",
        members: [
            {
                id: "simon-dao",
                name: "Simon Dao",
                role: "Digital Experience Lead",
                photo: "/MeetTheTeamPhotos/simon-dao.jpg",
                link: "https://www.linkedin.com/in/simon-dao/",
            },
            {
                id: "jonah-uellenberg",
                name: "Jonah Uellenberg",
                role: "Developer",
                photo: "/MeetTheTeamPhotos/jonah-uellenberg.jpg",
                link: "https://www.linkedin.com/in/uellenberg",
            },
            {
                id: "khushnain-gobindpuri",
                name: "Khushnain Gobindpuri",
                role: "Developer, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/khushnain-gobindpuri.png",
                link: "https://www.linkedin.com/in/khushnain-gobindpuri/",
            },
            {
                id: "sam-park",
                name: "Sam Park",
                role: "Developer",
                photo: "/MeetTheTeamPhotos/sam-park.jpg",
                link: "https://www.linkedin.com/in/sam-d-park/",
            },
            {
                id: "sohan-dandu",
                name: "Sohan Dandu",
                role: "Developer",
                photo: "/MeetTheTeamPhotos/default.jpg",
                link: undefined,
            }
        ],
    },
    {
        id: "local-arrangements",
        name: "Local Arrangement Liberators",
        members: [
            {
                id: "vinaya-chava",
                name: "Vinaya Chava",
                role: "Local Arrangements Lead",
                photo: "/MeetTheTeamPhotos/vinaya-chava.jpg",
                link: "https://www.linkedin.com/in/vinayachava/",
            },
            {
                id: "jui-bangali",
                name: "Jui Bangali",
                role: "WiCyS President, Local Arrangments Member, Product Management Member",
                photo: "/MeetTheTeamPhotos/jui-bangali.jpg",
                link: "https://www.linkedin.com/in/jui-bangali/",
            },
        ],
    },
    {
        id: "marketing",
        name: "Marketing Masterminds",
        members: [
            {
                id: "breanna-powell",
                name: "Breanna Powell",
                role: "Marketing Lead",
                photo: "/MeetTheTeamPhotos/breanna-powell.jpg",
                link: "https://www.linkedin.com/in/breanna-powell-wa/",
            },
            {
                id: "jesse-garcia",
                name: "Jesse Garcia",
                role: "BAP, Marketing Member",
                photo: "/MeetTheTeamPhotos/jesse-garcia.jpg",
                link: "https://www.linkedin.com/in/jesse-garcia-7116461a4/",
            },
            {
                id: "ruthie-lartey",
                name: "Ruthie Lartey",
                role: "Content and Design Co-lead, Marketing Member",
                photo: "/MeetTheTeamPhotos/ruthie-lartey.jpg",
                link: "https://www.linkedin.com/in/ruthie-lartey/",
            },
        ],
    },
    {
        id: "production-management",
        name: "Production Patriots",
        members: [
            {
                id: "hannah-kim",
                name: "Hannah Kim",
                role: "Production Management Lead",
                photo: "/MeetTheTeamPhotos/hannah-kim.jpg",
                link: "https://www.linkedin.com/in/hannah-hanul/",
            },
            {
                id: "jui-bangali",
                name: "Jui Bangali",
                role: "WiCyS President, Local Arrangments Member, Product Management Member",
                photo: "/MeetTheTeamPhotos/jui-bangali.jpg",
                link: "https://www.linkedin.com/in/jui-bangali/",
            },
        ],
    },
    {
        id: "sponsorships-outreach",
        name: "Sponsor Spartans",
        members: [
            {
                id: "chinmayee-chadalavada",
                name: "Chin Chadalavada",
                role: "Sponsorships Outreach Lead",
                photo: "/MeetTheTeamPhotos/chinmayee-chadalavada.jpg",
                link: "https://www.linkedin.com/in/chinmayee-chadalavada-4279a4243/",
            },
            {
                id: "ethan-leonard",
                name: "Ethan Leonard",
                role: "Sponsorships Outreach Co-Lead",
                photo: "/MeetTheTeamPhotos/ethan-leonard.png",
                link: "https://www.linkedin.com/in/ethan-s-leonard/",
            },
            {
                id: "justin-liao",
                name: "Justin Liao",
                role: "Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/justin-liao.png",
                link: "https://www.linkedin.com/in/justin-liao23/",
            },
            {
                id: "khushnain-gobindpuri",
                name: "Khushnain Gobindpuri",
                role: "Developer, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/khushnain-gobindpuri.png",
                link: "https://www.linkedin.com/in/khushnain-gobindpuri/",
            },
            {
                id: "lidia-workneh",
                name: "Lidia Workneh",
                role: "Product Management Member, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/default.jpg",
                link: "https://www.linkedin.com/in/lidia-workneh/",
            },
        ],
    },
];
