export const committees = [
    {
        id: "executives",
        name: "The Executives",
        members: [
            {
                id: "breanna-powell",
                name: "Breanna Powell",
                role: "Marketing Lead, Local Arrangements Member, Production Management Member, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/breanna-powell.jpg",
                link: "https://www.linkedin.com/in/breanna-powell-wa/",
            },
            {
                id: "chinmayee-chadalavada",
                name: "Chin Chadalavada",
                role: "Sponsorships Outreach Lead",
                photo: "/MeetTheTeamPhotos/chinmayee-chadalavada.jpg",
                link: "https://www.linkedin.com/in/chinmayee-chadalavada-4279a4243/",
            },
            {
                id: "hannah-kim",
                name: "Hannah Kim",
                role: "Production Management Lead",
                photo: "/MeetTheTeamPhotos/hannah-kim.jpg",
                link: "https://www.linkedin.com/in/hannah-hanul/",
            },
            {
                id: "sai-bathina",
                name: "Sai Bathina",
                role: "BCA, Avanade Rep, Content and Design Co-lead",
                photo: "/MeetTheTeamPhotos/sai-bathina.jpg",
                link: "https://www.linkedin.com/in/saikanishkbathina/",
            },
            {
                id: "simon-dao",
                name: "Simon Dao",
                role: "Website Development Lead",
                photo: "/MeetTheTeamPhotos/simon-dao.jpg",
                link: "https://www.linkedin.com/in/simon-dao/",
            },
            {
                id: "vinaya-chava",
                name: "Vinaya Chava",
                role: "Local Arrangements Lead",
                photo: "/MeetTheTeamPhotos/vinaya-chava.jpg",
                link: "https://www.linkedin.com/in/vinayachava/",
            },
        ],
    },
    {
        id: "committee-leads",
        name: "Justice Leads",
        members: [
            {
                id: "jonah-uellenberg",
                name: "Jonah Uellenberg",
                role: "Digital Experience Co-lead, Developer",
                photo: "/MeetTheTeamPhotos/jonah-uellenberg.jpg",
                link: "https://www.linkedin.com/in/uellenberg",
            },
            {
                id: "jui-bangali",
                name: "Jui Bangali",
                role: "WiCyS President, Local Arrangments Member, Product Management Member",
                photo: "/MeetTheTeamPhotos/jui-bangali.jpg",
                link: "https://www.linkedin.com/in/jui-bangali/",
            },
            {
                id: "kat-tran",
                name: "Kat Tran",
                role: "WiCyS Vice President, Developer, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/kat-tran.jpg",
                link: "https://www.linkedin.com/in/katqatran/",
            },
            {
                id: "lakshmi-srinivas",
                name: "Lakshmi Srinivas",
                role: "WiCyS Treasurer, Product Management Member",
                photo: "/MeetTheTeamPhotos/lakshmi-srinivas.png",
                link: "https://www.linkedin.com/in/lakshmikandagadlasrinivas/",
            },
            {
                id: "prarin-behdarvandian",
                name: "Prarin (Melody) Behdarvandian",
                role: "Content and Design Member, Marketing Member",
                photo: "/MeetTheTeamPhotos/prarin-behdarvandian.png",
                link: "https://www.linkedin.com/in/p-behdar/",
            },
            {
                id: "ruthie-lartey",
                name: "Ruthie Lartey",
                role: "ACM-W, Content and Design Co-lead, Marketing Member",
                photo: "/MeetTheTeamPhotos/ruthie-lartey.jpg",
                link: "https://www.linkedin.com/in/ruthie-lartey/",
            },
            {
                id: "sarinna-thaiy",
                name: "Sarinna Thaiy",
                role: "Content and Design, Husky Artist",
                photo: "/MeetTheTeamPhotos/sarinna-thaiy.jpg",
                link: "https://linkedin.com/in/sarinnathaiy",
            },
            {
                id: "jingyi-zhong",
                name: "Jing Yi Zhong",
                role: "Web Designer",
                photo: "/MeetTheTeamPhotos/jingyi-zhong.jpg",
                link: "https://www.linkedin.com/in/zhongjy/",
            },
        ],
    },
    {
        id: "content-design",
        name: "Content Design Champions",
        members: [
            {
                id: "ruthie-lartey",
                name: "Ruthie Lartey",
                role: "ACM-W, Content and Design Co-lead, Marketing Member",
                photo: "/MeetTheTeamPhotos/ruthie-lartey.jpg",
                link: "https://www.linkedin.com/in/ruthie-lartey/",
            },
            {
                id: "sai-bathina",
                name: "Sai Bathina",
                role: "BCA, Avanade Rep, Content and Design Co-lead",
                photo: "/MeetTheTeamPhotos/sai-bathina.jpg",
                link: "https://www.linkedin.com/in/saikanishkbathina/",
            },
            {
                id: "prarin-behdarvandian",
                name: "Prarin (Melody) Behdarvandian",
                role: "Content and Design Member, Marketing Member",
                photo: "/MeetTheTeamPhotos/prarin-behdarvandian.png",
                link: "https://www.linkedin.com/in/p-behdar/",
            },
            {
                id: "sai-rasajna-kolusu",
                name: "Rasajna Kolusu",
                role: "Content and Design Member, Marketing Member, Web Designer",
                photo: "/MeetTheTeamPhotos/sai-rasajna-kolusu.jpg",
                link: "https://www.linkedin.com/in/sai-rasajna-kolusu-091792319",
            },
            {
                id: "sarinna-thaiy",
                name: "Sarinna Thaiy",
                role: "Content and Design, Husky Artist",
                photo: "/MeetTheTeamPhotos/sarinna-thaiy.jpg",
                link: "https://linkedin.com/in/sarinnathaiy",
            },
            {
                id: "jingyi-zhong",
                name: "Jing Yi Zhong",
                role: "Web Designer",
                photo: "/MeetTheTeamPhotos/jingyi-zhong.jpg",
                link: "https://www.linkedin.com/in/zhongjy/",
            },
        ],
    },
    {
        id: "digital-experience",
        name: "Digital Daredevils",
        members: [
            {
                id: "simon-dao",
                name: "Simon Dao",
                role: "Digital Experience Lead",
                photo: "/MeetTheTeamPhotos/simon-dao.jpg",
                link: "https://www.linkedin.com/in/simon-dao/",
            },
            {
                id: "jonah-uellenberg",
                name: "Jonah Uellenberg",
                role: "Digital Experience Co-lead, Developer",
                photo: "/MeetTheTeamPhotos/jonah-uellenberg.jpg",
                link: "https://www.linkedin.com/in/uellenberg",
            },
            {
                id: "kat-tran",
                name: "Kat Tran",
                role: "WiCyS Vice President, Developer, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/kat-tran.jpg",
                link: "https://www.linkedin.com/in/katqatran/",
            },
            {
                id: "khushmeet-gobindpuri",
                name: "Meeti Gobindpuri",
                role: "Developer, Marketing Member",
                photo: "/MeetTheTeamPhotos/khushmeet-gobindpuri.jpg",
                link: "https://www.linkedin.com/in/khushmeetgobindpuri/",
            },
            {
                id: "khushnain-gobindpuri",
                name: "Khushnain Gobindpuri",
                role: "Developer, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/khushnain-gobindpuri.png",
                link: "https://www.linkedin.com/in/khushnain-gobindpuri/",
            },
            {
                id: "sai-rasajna-kolusu",
                name: "Rasajna Kolusu",
                role: "Content and Design Member, Marketing Member, Web Designer",
                photo: "/MeetTheTeamPhotos/sai-rasajna-kolusu.jpg",
                link: "https://www.linkedin.com/in/sai-rasajna-kolusu-091792319",
            },
            {
                id: "sam-park",
                name: "Sam Park",
                role: "Developer",
                photo: "/MeetTheTeamPhotos/sam-park.jpg",
                link: "https://www.linkedin.com/in/sam-d-park/",
            },
            {
                id: "sohan-dandu",
                name: "Sohan Dandu",
                role: "Developer",
                photo: "/MeetTheTeamPhotos/sohan-dandu.png",
                link: "https://www.linkedin.com/in/sohandandu/",
            },
        ],
    },
    {
        id: "local-arrangements",
        name: "Local Arrangement Liberators",
        members: [
            {
                id: "vinaya-chava",
                name: "Vinaya Chava",
                role: "Local Arrangements Lead",
                photo: "/MeetTheTeamPhotos/vinaya-chava.jpg",
                link: "https://www.linkedin.com/in/vinayachava/",
            },
            {
                id: "breanna-powell",
                name: "Breanna Powell",
                role: "Marketing Lead, Local Arrangements Member, Production Management Member, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/breanna-powell.jpg",
                link: "https://www.linkedin.com/in/breanna-powell-wa/",
            },
            {
                id: "jason-zhang",
                name: "Jason Zhang",
                role: "Local Arrangements Member, Marketing Member, Production Management Member",
                photo: "/MeetTheTeamPhotos/default.jpg",
                link: "https://linkedin.com/in/jasonzhng/",
            },
            {
                id: "jui-bangali",
                name: "Jui Bangali",
                role: "WiCyS President, Local Arrangements Member, Product Management Member",
                photo: "/MeetTheTeamPhotos/jui-bangali.jpg",
                link: "https://www.linkedin.com/in/jui-bangali/",
            },
            {
                id: "tarang-jammalamadaka",
                name: "Tarang (TJ) Jammalamadaka",
                role: "Local Arrangements Member, Marketing Member",
                photo: "/MeetTheTeamPhotos/tarang-jammalamadaka.png",
                link: "https://www.linkedin.com/in/tarang-tj/",
            },
        ],
    },
    {
        id: "marketing",
        name: "Marketing Masterminds",
        members: [
            {
                id: "breanna-powell",
                name: "Breanna Powell",
                role: "Marketing Lead, Local Arrangements Member, Production Management Member, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/breanna-powell.jpg",
                link: "https://www.linkedin.com/in/breanna-powell-wa/",
            },
            {
                id: "aatman-prajapati",
                name: "Aatman Prajapati",
                role: "Marketing Member",
                photo: "/MeetTheTeamPhotos/aatman-prajapati.jpg",
                link: "https://www.linkedin.com/in/aatmanrp/",
            },
            {
                id: "harshita-raghavan-vithyaa",
                name: "Harshita Raghavan Vithyaa",
                role: "Marketing Member",
                photo: "/MeetTheTeamPhotos/harshita-raghavan-vithyaa.jpg",
                link: "https://www.linkedin.com/in/harshita-rv-0a5419216/",
            },
            {
                id: "jane-choi",
                name: "Jane Choi",
                role: "Marketing Member",
                photo: "/MeetTheTeamPhotos/jane-choi.jpg",
                link: "https://www.linkedin.com/in/jane026/",
            },
            {
                id: "jason-zhang",
                name: "Jason Zhang",
                role: "Local Arrangements Member, Marketing Member, Production Management Member",
                photo: "/MeetTheTeamPhotos/default.jpg",
                link: "https://linkedin.com/in/jasonzhng/",
            },
            {
                id: "jesse-garcia",
                name: "Jesse Garcia",
                role: "BAP President, Marketing Member",
                photo: "/MeetTheTeamPhotos/jesse-garcia.jpg",
                link: "https://www.linkedin.com/in/jesse-garcia-7116461a4/",
            },
            {
                id: "khushmeet-gobindpuri",
                name: "Meeti Gobindpuri",
                role: "Developer, Marketing Member",
                photo: "/MeetTheTeamPhotos/khushmeet-gobindpuri.jpg",
                link: "https://www.linkedin.com/in/khushmeetgobindpuri/",
            },
            {
                id: "logan-choi",
                name: "Logan Choi",
                role: "Marketing Member",
                photo: "/MeetTheTeamPhotos/logan-choi.png",
                link: "https://www.linkedin.com/in/loganchoi/",
            },
            {
                id: "nandini-mistry",
                name: "Nandini Mistry",
                role: "Marketing Member",
                photo: "/MeetTheTeamPhotos/nandini-mistry.jpg",
                link: "https://www.linkedin.com/in/nandini-mistry-b7a38329a/",
            },
            {
                id: "prarin-behdarvandian",
                name: "Prarin (Melody) Behdarvandian",
                role: "Content and Design Member, Marketing Member",
                photo: "/MeetTheTeamPhotos/prarin-behdarvandian.png",
                link: "https://www.linkedin.com/in/p-behdar/",
            },
            {
                id: "rachel-baatz",
                name: "Rachel Baatz",
                role: "Marketing Member",
                photo: "/MeetTheTeamPhotos/rachel-baatz.jpg",
                link: "https://www.linkedin.com/in/rachel-baatz/",
            },
            {
                id: "ruthie-lartey",
                name: "Ruthie Lartey",
                role: "Content and Design Co-lead, Marketing Member",
                photo: "/MeetTheTeamPhotos/ruthie-lartey.jpg",
                link: "https://www.linkedin.com/in/ruthie-lartey/",
            },
            {
                id: "sai-rasajna-kolusu",
                name: "Rasajna Kolusu",
                role: "Content and Design Member, Marketing Member, Web Designer",
                photo: "/MeetTheTeamPhotos/sai-rasajna-kolusu.jpg",
                link: "https://www.linkedin.com/in/sai-rasajna-kolusu-091792319",
            },
            {
                id: "tarang-jammalamadaka",
                name: "Tarang (TJ) Jammalamadaka",
                role: "Local Arrangements Member, Marketing Member",
                photo: "/MeetTheTeamPhotos/tarang-jammalamadaka.png",
                link: "https://www.linkedin.com/in/tarang-tj/",
            },
        ],
    },
    {
        id: "production-management",
        name: "Production Patriots",
        members: [
            {
                id: "hannah-kim",
                name: "Hannah Kim",
                role: "Production Management Lead",
                photo: "/MeetTheTeamPhotos/hannah-kim.jpg",
                link: "https://www.linkedin.com/in/hannah-hanul/",
            },
            {
                id: "breanna-powell",
                name: "Breanna Powell",
                role: "Marketing Lead, Local Arrangements Member, Production Management Member, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/breanna-powell.jpg",
                link: "https://www.linkedin.com/in/breanna-powell-wa/",
            },
            {
                id: "jason-zhang",
                name: "Jason Zhang",
                role: "Local Arrangements Member, Marketing Member, Production Management Member",
                photo: "/MeetTheTeamPhotos/default.jpg",
                link: "https://linkedin.com/in/jasonzhng/",
            },
            {
                id: "jui-bangali",
                name: "Jui Bangali",
                role: "WiCyS President, Local Arrangments Member, Product Management Member",
                photo: "/MeetTheTeamPhotos/jui-bangali.jpg",
                link: "https://www.linkedin.com/in/jui-bangali/",
            },
            {
                id: "lakshmi-srinivas",
                name: "Lakshmi Srinivas",
                role: "WiCyS Treasurer, Product Management Member",
                photo: "/MeetTheTeamPhotos/lakshmi-srinivas.png",
                link: "https://www.linkedin.com/in/lakshmikandagadlasrinivas/",
            },
            {
                id: "ryan-chiang",
                name: "Ryan Chiang",
                role: "Product Management Member",
                photo: "/MeetTheTeamPhotos/default.jpg",
                link: "https://www.linkedin.com/in/ryankuen/",
            },
        ],
    },
    {
        id: "sponsorships-outreach",
        name: "Sponsor Spartans",
        members: [
            {
                id: "chinmayee-chadalavada",
                name: "Chin Chadalavada",
                role: "Sponsorships Outreach Lead",
                photo: "/MeetTheTeamPhotos/chinmayee-chadalavada.jpg",
                link: "https://www.linkedin.com/in/chinmayee-chadalavada-4279a4243/",
            },
            {
                id: "ethan-leonard",
                name: "Ethan Leonard",
                role: "Sponsorships Outreach Co-Lead",
                photo: "/MeetTheTeamPhotos/ethan-leonard.png",
                link: "https://www.linkedin.com/in/ethan-s-leonard/",
            },
            {
                id: "justin-liao",
                name: "Justin Liao",
                role: "Sponsorships Outreach Co-Lead",
                photo: "/MeetTheTeamPhotos/justin-liao.png",
                link: "https://www.linkedin.com/in/justin-liao23/",
            },
            {
                id: "breanna-powell",
                name: "Breanna Powell",
                role: "Marketing Lead, Local Arrangements Member, Production Management Member, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/breanna-powell.jpg",
                link: "https://www.linkedin.com/in/breanna-powell-wa/",
            },
            {
                id: "kat-tran",
                name: "Kat Tran",
                role: "WiCyS Vice President, Developer, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/kat-tran.jpg",
                link: "https://www.linkedin.com/in/katqatran/",
            },
            {
                id: "khushnain-gobindpuri",
                name: "Khushnain Gobindpuri",
                role: "Developer, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/khushnain-gobindpuri.png",
                link: "https://www.linkedin.com/in/khushnain-gobindpuri/",
            },
            {
                id: "lidia-workneh",
                name: "Lidia Workneh",
                role: "Product Management Member, Sponsorships Outreach Member",
                photo: "/MeetTheTeamPhotos/default.jpg",
                link: "https://www.linkedin.com/in/lidia-workneh/",
            },
        ],
    },
];
